# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KartHazirlama.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AnaPencere(object):
    def setupUi(self, AnaPencere):
        ag = QtWidgets.QDesktopWidget().availableGeometry()
        sg = QtWidgets.QDesktopWidget().screenGeometry()

        widget = AnaPencere.geometry()
        x = ag.width() - widget.width()
        y = 2 * ag.height() - sg.height() - widget.height()
        AnaPencere.move(x, y)

        AnaPencere.setObjectName("AnaPencere")
        AnaPencere.resize(291, 301)
        self.centralwidget = QtWidgets.QWidget(AnaPencere)
        self.centralwidget.setObjectName("centralwidget")
        self.kartDurum = QtWidgets.QPushButton(self.centralwidget)
        self.kartDurum.setEnabled(False)
        self.kartDurum.setGeometry(QtCore.QRect(-20, -8, 331, 31))
        self.kartDurum.setText("")
        self.kartDurum.setObjectName("kartDurum")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(200, 200, 81, 24))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setMaximum(9999.99)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.lblTip = QtWidgets.QLabel(self.centralwidget)
        self.lblTip.setGeometry(QtCore.QRect(150, 60, 121, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblTip.setFont(font)
        self.lblTip.setText("")
        self.lblTip.setObjectName("lblTip")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lblAlias = QtWidgets.QLabel(self.centralwidget)
        self.lblAlias.setGeometry(QtCore.QRect(150, 30, 101, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblAlias.setFont(font)
        self.lblAlias.setObjectName("lblAlias")
        self.lblEskiBakiye = QtWidgets.QLabel(self.centralwidget)
        self.lblEskiBakiye.setGeometry(QtCore.QRect(200, 140, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblEskiBakiye.setFont(font)
        self.lblEskiBakiye.setObjectName("lblEskiBakiye")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 240, 261, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lblVize = QtWidgets.QLabel(self.centralwidget)
        self.lblVize.setGeometry(QtCore.QRect(150, 90, 141, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblVize.setFont(font)
        self.lblVize.setText("")
        self.lblVize.setObjectName("lblVize")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 200, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 151, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 121, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lblDurum = QtWidgets.QLabel(self.centralwidget)
        self.lblDurum.setGeometry(QtCore.QRect(10, 260, 271, 31))
        self.lblDurum.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDurum.setObjectName("lblDurum")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 131, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lblGuncelBakiye = QtWidgets.QLabel(self.centralwidget)
        self.lblGuncelBakiye.setGeometry(QtCore.QRect(200, 170, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblGuncelBakiye.setFont(font)
        self.lblGuncelBakiye.setObjectName("lblGuncelBakiye")
        AnaPencere.setCentralWidget(self.centralwidget)

        self.retranslateUi(AnaPencere)
        QtCore.QMetaObject.connectSlotsByName(AnaPencere)

    def retranslateUi(self, AnaPencere):
        _translate = QtCore.QCoreApplication.translate
        AnaPencere.setWindowTitle(_translate("AnaPencere", "Bakiye Yükleme"))
        self.label_11.setText(_translate("AnaPencere", "GÜNCEL BAKIYE : "))
        self.label_7.setText(_translate("AnaPencere", "ESKİ BAKİYE"))
        self.lblAlias.setText(_translate("AnaPencere", "0000000"))
        self.lblEskiBakiye.setText(_translate("AnaPencere", "0.00TL"))
        self.label_10.setText(_translate("AnaPencere", "YÜKLENECEK :"))
        self.label.setText(_translate("AnaPencere", "MÜŞTERİ NO : "))
        self.label_3.setText(_translate("AnaPencere", "KART TİPİ : "))
        self.lblDurum.setText(_translate("AnaPencere", "YÜKLENECEK MİKTARI GİRİN"))
        self.label_4.setText(_translate("AnaPencere", "VIZE TARİHİ : "))
        self.lblGuncelBakiye.setText(_translate("AnaPencere", "0.00TL"))

